name: Build and (maybe) push Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

env:
  BUILD_PLATFORMS: linux/amd64, linux/arm64

jobs:
  build-php-images:
    name: Build PHP images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.event_name != 'release' }}
      matrix:
        php: ["8.1", "8.0", "7.4"]
        type: ["php-fpm", "cli"]
        include:
          - type: php-fpm
            type_short: fpm

          - type: cli
            type_short: cli
    steps:
      - name: Set env
        run: |
          echo "PROD_IMAGE_REF=mutationdigitale/${{ matrix.type }}:${{ matrix.php }}" >> $GITHUB_ENV
          echo "DEV_IMAGE_REF=mutationdigitale/${{ matrix.type }}:${{ matrix.php }}-dev" >> $GITHUB_ENV
          echo "PROD_DOCKERFILE=${{ matrix.php }}/Dockerfile" >> $GITHUB_ENV
          echo "DEV_DOCKERFILE=${{ matrix.php }}/dev.Dockerfile" >> $GITHUB_ENV

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name == 'release'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push production image
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          context: ${{ matrix.php }}
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.PROD_IMAGE_REF }}
          build-args: |
            PROJECT_TYPE=${{ matrix.type_short }}
            PHP_VERSION=${{ matrix.php }}

      - name: Build & push development image
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          context: ${{ matrix.php }}
          file: ${{ env.DEV_DOCKERFILE }}
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.DEV_IMAGE_REF }}
          build-args: |
            PROJECT_TYPE=${{ matrix.type }}
            PHP_VERSION=${{ matrix.php }}

  build-nginx-images:
      name: Build NGINX images
      needs: build-php-images
      runs-on: ubuntu-latest
      strategy:
        fail-fast: ${{ github.event_name != 'release' }}
        matrix:
          php: ["8.1", "8.0", "7.4"]
      steps:
        - name: Set env
          run: |
            echo "PROD_IMAGE_REF=mutationdigitale/nginx:${{ matrix.php }}" >> $GITHUB_ENV
            echo "DEV_IMAGE_REF=mutationdigitale/nginx:${{ matrix.php }}-dev" >> $GITHUB_ENV
            echo "BASE_PROD_IMAGE_TAG=${{ matrix.php }}" >> $GITHUB_ENV
            echo "BASE_DEV_IMAGE_TAG=${{ matrix.php }}-dev" >> $GITHUB_ENV

        - name: Check out the repository
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          with:
            install: true

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          if: github.event_name == 'release'
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build & push production image
          uses: docker/build-push-action@v2
          if: github.event_name == 'release'
          with:
            context: nginx
            push: true
            platforms: ${{ env.BUILD_PLATFORMS }}
            tags: ${{ env.PROD_IMAGE_REF }}
            build-args: |
              PHP_VERSION=${{ env.BASE_PROD_IMAGE_TAG }}

        - name: Build & push development image
          uses: docker/build-push-action@v2
          if: github.event_name == 'release'
          with:
            context: nginx
            push: true
            platforms: ${{ env.BUILD_PLATFORMS }}
            tags: ${{ env.DEV_IMAGE_REF }}
            build-args: |
              PHP_VERSION=${{ env.BASE_DEV_IMAGE_TAG }}
              NGINX_CONF=dev.default.conf
