name: Build and (maybe) Push Docker Images
on:
  push:
    branches:
      - gha-test
env:
  BUILD_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.event_name != 'release' }}
      matrix:
        php: ["8.0"]
    name: gha test ${{ matrix.php }} images
    env:
      PHP_IMAGE_TAG: timkelty/gha-test:${{ matrix.php }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: timkelty
          password: ${{ secrets.DOCKERHUB_TOKEN_TIM }}

      - name: Build ${{ env.PHP_IMAGE_TAG }}
        uses: docker/build-push-action@v2
        with:
          context: gha-test
          file: gha-test/Dockerfile
          push: false
          load: true
          tags: ${{ env.PHP_IMAGE_TAG }}
          build-args: |
            PROJECT_TYPE=fpm
            PHP_VERSION=${{ matrix.php }}

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.PHP_IMAGE_TAG }}
          args: --file=gha-test/Dockerfile

      - name: Push timkelty/gha-test:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: gha-test
          file: gha-test/Dockerfile
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.PHP_IMAGE_TAG }}
          build-args: |
            PROJECT_TYPE=fpm
            PHP_VERSION=${{ matrix.php }}
