name: Build and (maybe) Push Docker Images
on:
  push:
    branches:
      - gha-test
env:
  BUILD_PLATFORMS: linux/amd64, linux/arm64
jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.event_name != 'release' }}
      matrix:
        php: ["8.1-rc", "8.0", "7.4", "7.3"]
        type: ["fpm", "cli"]
        include:
          - type: fpm
            image_name: timkelty/php-fpm

          - type: cli
            image_name: timkelty/cli

    name: Build & Push Image
    steps:
      - name: Set IMAGE_TAG env
        run: |
          echo "IMAGE_TAG=${{ matrix.image_name }}:${{ matrix.php }}" >> $GITHUB_ENV
          echo "CONTEXT=${{ matrix.context || matrix.php }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        # if: github.event_name == 'release'
        with:
          username: timkelty
          password: ${{ secrets.DOCKERHUB_TOKEN_TIM }}

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT }}
          push: false
          load: true
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            PROJECT_TYPE=${{ matrix.type }}
            PHP_VERSION=${{ matrix.php }}

      - name: Snyk test
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_TAG }}

      - name: Build & push image
        uses: docker/build-push-action@v2
        # if: github.event_name == 'release'
        with:
          context: ${{ env.CONTEXT }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            PROJECT_TYPE=${{ matrix.type }}
            PHP_VERSION=${{ matrix.php }}

      - name: Build nginx image
        if: matrix.type == 'fpm'
        uses: docker/build-push-action@v2
        with:
          context: nginx
          push: false
          load: true
          tags: timkelty/nginx:${{ matrix.php }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}

      - name: Build dev image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/dev.Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_TAG }}-dev
          build-args: |
            PROJECT_TYPE=${{ matrix.type }}
            PHP_VERSION=${{ matrix.php }}
