name: Build and (maybe) Push Docker Images
on:
  push:
    branches:
      - gha-test

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.event_name != 'release' }}
      matrix:
        php: ["8.0"]
    name: gha test ${{ matrix.php }} images
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: timkelty
          password: ${{ secrets.DOCKERHUB_TOKEN_TIM }}

      - name: Build timkelty/gha-test:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ${{ matrix.php }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: timkelty/gha-test:${{ matrix.php }}
          build-args: |
            PROJECT_TYPE=fpm
            PHP_VERSION=${{ matrix.php }}
