name: Build and (maybe) Push Docker Images
on:
  push:
    branches:
      - gha-test
env:
  BUILD_PLATFORMS: linux/amd64, linux/arm64

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.event_name != 'release' }}
      matrix:
        php: ["8.0", "7.4"]
        type: ["gha-test-fpm", "gha-test-cli"]
        include:
          - type: gha-test-fpm
            image_tag: timkelty/gha-test-php-fpm:${{ matrix.php }}

          - type: gha-test-cli
            image_tag: timkelty/gha-test-cli:${{ matrix.php }}
    name: gha test ${{ matrix.image_tag }}
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: timkelty
          password: ${{ secrets.DOCKERHUB_TOKEN_TIM }}

      - name: Build ${{ matrix.image_tag }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.type }}
          file: ${{ matrix.type }}/test.Dockerfile
          push: false
          load: true
          tags: ${{ matrix.image_tag }}
          build-args: |
            PROJECT_TYPE=${{ matrix.type}}
            PHP_VERSION=${{ matrix.php }}


      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ matrix.image_tag }}

      - name: Push ${{ matrix.image_tag }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.type }}
          file: ${{ matrix.type }}/test.Dockerfile
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ matrix.image_tag }}
          build-args: |
            PROJECT_TYPE=${{ matrix.type }}
            PHP_VERSION=${{ matrix.php }}
